language: c++

sudo: required

os:
  - linux

services:
  - docker

install:
  - docker pull raisim/raicommon:latest
  - docker run -itd -v $TRAVIS_BUILD_DIR:$TRAVIS_BUILD_DIR --name raicommon-docker raisim/simbenchmark:latest

script:
  - docker exec raicommon-docker /bin/bash -c "cd $TRAVIS_BUILD_DIR && ./.ci/build.sh"
